### ISSUE TITLE
Umfrage erstellen

### ISSUE THREAD

**Issue by mrente33** [laughing7y/magicMeshRoom#17]
Personen ab 16
Berufskolleg, Gymnasium, Gesamtschule
Männlich, Weiblich, Diverse
vielleicht Fokus auf weiblich (aber da bräuchten wir einen speziellen Theorieteil)
Thema: Zauberei, GoT ...

**Comment by laughing7y** [comment]
Rico kümmert sich um Fragebogen.

**Comment by mrente33** [comment]
https://www.soscisurvey.de/meshroom/?act=ggPIOF2WsqLrZvmQ8HhBBTow


erster Pretest, bitte mal anschauen @laughing7y @JonasHohendahl

**Comment by mrente33** [comment]
https://www.soscisurvey.de/meshroom/

der Link zum Fragebogen!

**Comment by laughing7y** [comment]
Nice
